# Generated by Django 4.2.6 on 2023-10-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
