# Generated by Django 4.2.6 on 2023-10-23 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_topic_alter_news_published_at_news_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.topic'),
        ),
    ]
