# Generated by Django 4.2.6 on 2023-10-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.CharField(),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
