# Generated by Django 4.2.6 on 2023-10-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_description_news_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='published_at',
            new_name='date',
        ),
    ]
