# Generated by Django 4.2.6 on 2023-10-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_title'),
        ('news', '0007_alter_news_date_alter_news_title'),
    ]

    operations = [
    ]
